# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
      timezone: "Europe/Berlin"
      day: "sunday"
      time: "05:00"
    commit-message:
      prefix: "chore(ci): "
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "doc/"
    schedule:
      interval: "quarterly"
      timezone: "Europe/Berlin"
      day: "sunday"
      time: "05:00"
    commit-message:
      prefix: "chore(doc): "
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "sphinx"
        update-types:
          - "version-update:semver-major"
